import pg from 'pg';
import { randomUUID } from 'node:crypto';
import { readConfig } from '../packages/core/src/config.js';
import { migrate } from '../packages/core/src/db/migrate.js';
import { seed } from '../packages/core/src/db/seed.js';
import { setCartItem } from '../packages/core/src/domain/checkout.js';
import { variantFor } from '../packages/core/src/domain/followups.js';
import { createAgentModels } from '../packages/core/src/agents/models.js';
import { startFollowupWorker } from '../packages/core/src/followup-worker.js';

// Explicit accelerated demonstration, isolated from storefront data and queue.
// Does not modify .env or the normal 30-minute deadline.
const config = readConfig();
const schema = `test_live_followups_${randomUUID().replaceAll('-', '')}`;
const admin = new pg.Pool({ connectionString: config.DATABASE_URL });
const db = new pg.Pool({
  connectionString: config.DATABASE_URL,
  options: `-c search_path=${schema}`,
  max: 10,
});
let runtime: Awaited<ReturnType<typeof startFollowupWorker>> | undefined;
try {
  await admin.query(`CREATE SCHEMA "${schema}"`);
  await migrate(db);
  await seed(db);
  const ids = (await db.query('SELECT id FROM customers ORDER BY id')).rows.map(
    (r) => r.id as string,
  );
  const selected = ['A', 'B'].map((variant) => ids.find((id) => variantFor(id) === variant)!);
  for (const [index, id] of selected.entries()) {
    const text =
      index === 0
        ? 'Ce foulard me plaît, je réfléchis à la couleur avant de terminer mon panier.'
        : '3jebni had foulard, baqi kanfker f la couleur qbel mankemmel panier.';
    await db.query(
      'INSERT INTO conversations(customer_id,last_client_message_at) VALUES ($1,now())',
      [id],
    );
    const turn = randomUUID();
    await db.query(
      "INSERT INTO chat_turns(id,customer_id,input,status) VALUES ($1,$2,$3,'completed')",
      [turn, id, text],
    );
    await db.query(
      "INSERT INTO chat_messages(customer_id,turn_id,role,content) VALUES ($1,$2,'user',$3)",
      [id, turn, text],
    );
    await setCartItem(db, id, { ref: 'REF-0006', quantity: 1 });
  }
  const models = createAgentModels(config);
  console.info(
    'Explicit DEMO: 3-second delay, synthetic carts, isolated PostgreSQL schema and Redis queue.',
  );
  runtime = await startFollowupWorker({
    db,
    redisUrl: config.REDIS_URL,
    models: { decide: models.followup, audit: models.audit },
    delayMs: 3000,
    queueName: `test-live-followups-${randomUUID()}`,
    reconcileMs: 500,
  });
  const deadline = Date.now() + 120000;
  while (Date.now() < deadline) {
    const rows = (await db.query('SELECT status FROM followups')).rows;
    if (rows.length === 2 && rows.every((row) => row.status !== 'pending')) break;
    await new Promise((resolve) => setTimeout(resolve, 500));
  }
  const rows = (
    await db.query(
      'SELECT variant,status,reason,sent_at>=due_at AS deadline_respected FROM followups ORDER BY variant',
    )
  ).rows;
  console.info(JSON.stringify({ stage: 'live_followups', rows }));
  if (rows.length !== 2 || rows.some((row) => row.status !== 'sent' || !row.deadline_respected))
    throw new Error('FOLLOWUP_CHECK_FAILED');
  console.info('Both variants generated by the live model, audited and delivered by BullMQ.');
} catch {
  console.error('Live follow-up diagnostic failed; inspect sanitized stage results.');
  process.exitCode = 1;
} finally {
  if (runtime) {
    await runtime.worker.close();
    await runtime.queue.obliterate({ force: true });
    await runtime.close();
  }
  await db.end();
  await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
  await admin.end();
}
